name: spamtp
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - adwaita-icon-theme=49.0
  - anyio=4.11.0
  - aom=3.9.1
  - argcomplete=3.6.2
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - attr=2.5.2
  - attrs=25.4.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - binutils_impl_linux-64=2.44
  - bioconductor-affy=1.84.0
  - bioconductor-affyio=1.76.0
  - bioconductor-annotationfilter=1.30.0
  - bioconductor-assorthead=1.0.0
  - bioconductor-beachmat=2.22.0
  - bioconductor-biobase=2.66.0
  - bioconductor-biocbaseutils=1.8.0
  - bioconductor-biocgenerics=0.52.0
  - bioconductor-biocneighbors=2.0.0
  - bioconductor-biocparallel=1.40.0
  - bioconductor-biocsingular=1.22.0
  - bioconductor-data-packages=20250625
  - bioconductor-delayedarray=0.32.0
  - bioconductor-delayedmatrixstats=1.28.0
  - bioconductor-ebimage=4.48.0
  - bioconductor-edger=4.4.0
  - bioconductor-enhancedvolcano=1.24.0
  - bioconductor-fgsea=1.32.2
  - bioconductor-genomeinfodb=1.42.0
  - bioconductor-genomeinfodbdata=1.2.13
  - bioconductor-genomicranges=1.58.0
  - bioconductor-hdf5array=1.34.0
  - bioconductor-impute=1.80.0
  - bioconductor-iranges=2.40.0
  - bioconductor-limma=3.62.1
  - bioconductor-matrixgenerics=1.18.0
  - bioconductor-mscoreutils=1.18.0
  - bioconductor-msnbase=2.32.0
  - bioconductor-multiassayexperiment=1.32.0
  - bioconductor-mzid=1.44.0
  - bioconductor-mzr=2.40.0
  - bioconductor-pcamethods=1.98.0
  - bioconductor-preprocesscore=1.68.0
  - bioconductor-protgenerics=1.38.0
  - bioconductor-psmatch=1.10.0
  - bioconductor-qfeatures=1.16.0
  - bioconductor-rhdf5=2.50.0
  - bioconductor-rhdf5filters=1.18.0
  - bioconductor-rhdf5lib=1.28.0
  - bioconductor-s4arrays=1.6.0
  - bioconductor-s4vectors=0.44.0
  - bioconductor-scaledmatrix=1.14.0
  - bioconductor-scater=1.34.1
  - bioconductor-scuttle=1.16.0
  - bioconductor-singlecellexperiment=1.28.0
  - bioconductor-sparsearray=1.6.0
  - bioconductor-sparsematrixstats=1.18.0
  - bioconductor-summarizedexperiment=1.36.0
  - bioconductor-ucsc.utils=1.2.0
  - bioconductor-vsn=3.74.0
  - bioconductor-xvector=0.46.0
  - bioconductor-zlibbioc=1.52.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.6
  - brotli-python=1.1.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.3
  - comm=0.2.3
  - curl=8.14.1
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - epoxy=1.5.10
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fqdn=1.5.1
  - freetype=2.14.1
  - freexl=2.0.0
  - fribidi=1.0.16
  - gcc_impl_linux-64=15.2.0
  - gdk-pixbuf=2.42.12
  - geos=3.13.0
  - geotiff=1.7.4
  - gfortran_impl_linux-64=15.2.0
  - ghostscript=10.06.0
  - giflib=5.2.2
  - glib-tools=2.84.1
  - glpk=5.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - graphviz=12.2.1
  - gsl=2.7
  - gtk3=3.24.43
  - gts=0.7.6
  - gxx_impl_linux-64=15.2.0
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=11.2.1
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hicolor-icon-theme=0.17
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagemagick=7.1.1_47
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.37.0
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jbig=2.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jq=1.5
  - json-c=0.18
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter=1.1.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.9
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kernel-headers_linux-64=4.18.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - lark=1.3.0
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarchive=3.7.7
  - libavif16=1.3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libconfig=1.7.3
  - libcups=2.3.3
  - libcurl=8.14.1
  - libde265=1.0.15
  - libdeflate=1.23
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libegl-devel=1.7.0
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=15.2.0
  - libgcc-ng=15.2.0
  - libgd=2.3.3
  - libgdal-core=3.10.2
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libgl-devel=1.7.0
  - libglib=2.84.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libglx-devel=1.7.0
  - libgomp=15.2.0
  - libheif=1.19.7
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.9.3
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libpciaccess=0.18
  - libpng=1.6.50
  - librsvg=2.58.4
  - librttopo=1.1.0
  - libsanitizer=15.2.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.0
  - libudunits2=2.2.28
  - libuuid=2.41.2
  - libuv=1.51.0
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.8
  - libzip=1.11.2
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - make=4.4.1
  - markupsafe=3.0.3
  - matplotlib-inline=0.1.7
  - minizip=4.0.10
  - mistune=3.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.4.7
  - notebook-shim=0.2.4
  - openjpeg=2.5.3
  - openssl=3.5.4
  - overrides=7.7.0
  - packaging=25.0
  - pandoc=3.8.2
  - pandocfilters=1.5.0
  - pango=1.56.3
  - parso=0.8.5
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - pixman=0.46.4
  - pkg-config=0.29.2
  - platformdirs=4.4.0
  - proj=9.5.1
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - r-abind=1.4_8
  - r-askpass=1.2.1
  - r-base=4.4.3
  - r-base64enc=0.1_3
  - r-beeswarm=0.4.0
  - r-bh=1.87.0_1
  - r-biocmanager=1.30.26
  - r-bit=4.6.0
  - r-bit64=4.6.0_1
  - r-bitops=1.0_9
  - r-bslib=0.9.0
  - r-cachem=1.1.0
  - r-cairo=1.6_2
  - r-catools=1.18.3
  - r-class=7.3_23
  - r-classint=0.4_11
  - r-cli=3.6.5
  - r-clue=0.3_66
  - r-cluster=2.1.8.1
  - r-codetools=0.2_20
  - r-colorspace=2.1_2
  - r-commonmark=2.0.0
  - r-cowplot=1.2.0
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-crosstalk=1.2.2
  - r-curl=7.0.0
  - r-data.table=1.17.8
  - r-dbi=1.2.3
  - r-deldir=2.0_4
  - r-digest=0.6.37
  - r-doparallel=1.0.17
  - r-dotcall64=1.2
  - r-dplyr=1.1.4
  - r-dqrng=0.3.2
  - r-e1071=1.7_16
  - r-ellipsis=0.3.2
  - r-evaluate=1.0.5
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastdummies=1.7.5
  - r-fastmap=1.2.0
  - r-fastmatch=1.1_6
  - r-fftwtools=0.9_11
  - r-fields=17.1
  - r-fitdistrplus=1.2_4
  - r-fnn=1.1.4.1
  - r-fontawesome=0.5.3
  - r-foreach=1.5.2
  - r-formatr=1.14
  - r-fs=1.6.6
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-future=1.67.0
  - r-future.apply=1.20.0
  - r-generics=0.1.4
  - r-ggbeeswarm=0.7.2
  - r-ggdendro=0.2.0
  - r-ggnewscale=0.5.2
  - r-ggplot2=4.0.0
  - r-ggrastr=1.0.2
  - r-ggrepel=0.9.6
  - r-ggridges=0.5.7
  - r-globals=0.18.0
  - r-glue=1.8.0
  - r-goftest=1.2_3
  - r-gplots=3.2.0
  - r-gridextra=2.3
  - r-gtable=0.3.6
  - r-gtools=3.9.5
  - r-hdf5r=1.3.12
  - r-here=1.0.2
  - r-hexbin=1.28.5
  - r-highr=0.11
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpuv=1.6.16
  - r-httr=1.4.7
  - r-ica=1.0_3
  - r-igraph=2.1.4
  - r-irdisplay=1.1
  - r-irkernel=1.3.2
  - r-irlba=2.3.5.1
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jpeg=0.1_11
  - r-jquerylib=0.1.4
  - r-jsonlite=2.0.0
  - r-kernsmooth=2.23_26
  - r-knitr=1.50
  - r-labeling=0.4.3
  - r-lambda.r=1.2.4
  - r-later=1.4.4
  - r-lattice=0.22_7
  - r-lazyeval=0.2.2
  - r-leidenbase=0.1.32
  - r-lifecycle=1.0.4
  - r-listenv=0.9.1
  - r-lmtest=0.9_40
  - r-locfit=1.5_9.12
  - r-magick=2.8.6
  - r-magrittr=2.0.4
  - r-maldiquant=1.22.3
  - r-maps=3.4.3
  - r-mass=7.3_65
  - r-matrix=1.7_4
  - r-matrixstats=1.5.0
  - r-memoise=2.0.1
  - r-mime=0.13
  - r-miniui=0.1.2
  - r-munsell=0.5.1
  - r-naturalsort=0.1.3
  - r-ncdf4=1.24
  - r-nlme=3.1_168
  - r-ontologyindex=2.12
  - r-openssl=2.3.4
  - r-parallelly=1.45.1
  - r-patchwork=1.3.2
  - r-pbapply=1.7_4
  - r-pbdzmq=0.3_14
  - r-pheatmap=1.0.13
  - r-pillar=1.11.1
  - r-pkgconfig=2.0.3
  - r-plotly=4.11.0
  - r-plyr=1.8.9
  - r-png=0.1_8
  - r-polyclip=1.10_7
  - r-progressr=0.16.0
  - r-promises=1.3.3
  - r-proxy=0.4_27
  - r-purrr=1.1.0
  - r-r.methodss3=1.8.2
  - r-r.oo=1.27.1
  - r-r.utils=2.13.0
  - r-r6=2.6.1
  - r-ragg=1.5.0
  - r-rann=2.6.2
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.1.0
  - r-rcppannoy=0.0.22
  - r-rcpparmadillo=15.0.2_2
  - r-rcppeigen=0.3.4.0.2
  - r-rcpphnsw=0.6.0
  - r-rcppml=0.3.7
  - r-rcppprogress=0.4.2
  - r-rcpptoml=0.2.3
  - r-rcurl=1.98_1.17
  - r-repr=1.1.7
  - r-reshape2=1.4.4
  - r-reticulate=1.43.0
  - r-rlang=1.1.6
  - r-rmarkdown=2.30
  - r-rocr=1.0_11
  - r-rprojroot=2.1.1
  - r-rspectra=0.16_2
  - r-rsvd=1.0.5
  - r-rtsne=0.17
  - r-s2=1.1.9
  - r-s7=0.2.0
  - r-sass=0.4.10
  - r-scales=1.4.0
  - r-scattermore=1.2
  - r-sctransform=0.4.2
  - r-seurat=5.3.0
  - r-seuratobject=5.2.0
  - r-sf=1.0_20
  - r-shiny=1.11.1
  - r-shinyjs=2.1.0
  - r-sitmo=2.0.2
  - r-snow=0.4_4
  - r-sourcetools=0.1.7_1
  - r-sp=2.2_0
  - r-spam=2.11_1
  - r-spatstat.data=3.1_8
  - r-spatstat.explore=3.5_3
  - r-spatstat.geom=3.6_0
  - r-spatstat.random=3.4_2
  - r-spatstat.sparse=3.1_0
  - r-spatstat.univar=3.1_4
  - r-spatstat.utils=3.2_0
  - r-statmod=1.5.0
  - r-stringi=1.8.7
  - r-stringr=1.5.2
  - r-survival=3.8_3
  - r-sys=3.4.3
  - r-systemfonts=1.3.1
  - r-tensor=1.5.1
  - r-textshaping=1.0.1
  - r-tibble=3.3.0
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tiff=0.1_12
  - r-tinytex=0.57
  - r-units=0.8_7
  - r-utf8=1.2.6
  - r-uuid=1.2_1
  - r-uwot=0.2.3
  - r-vctrs=0.6.5
  - r-vipor=0.4.7
  - r-viridis=0.6.5
  - r-viridislite=0.4.2
  - r-withr=3.0.2
  - r-wk=0.9.4
  - r-xfun=0.53
  - r-xml=3.99_0.17
  - r-xtable=1.8_4
  - r-yaml=2.3.10
  - r-zeallot=0.2.0
  - r-zoo=1.8_14
  - rav1e=0.7.1
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.27.1
  - sed=4.9
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8
  - sqlite=3.50.4
  - stack_data=0.6.3
  - svt-av1=3.1.2
  - sysroot_linux-64=2.28
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.2.1
  - tomlkit=0.13.3
  - tornado=6.5.2
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250822
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - wayland=1.24.0
  - wcwidth=0.2.14
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - x265=3.5
  - xerces-c=3.2.5
  - xkeyboard-config=2.46
  - xmltodict=1.0.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - yaml=0.2.5
  - yq=3.4.3
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7