# Publication Scripts

This folder contains scripts and notebooks used to generate figures for the SpaMTP manuscript. These files are provided **for transparency and reproducibility** for those manuscript figures which are not included in the tutorials/vignettes provided on the [SpaMTP website](https://genomicsmachinelearning.github.io/SpaMTP/). The locations of code segments for each manuscript figure are linked in the table below. 



| Figure | Panel | Files |
|------:|:-----:|-------------|
| Figure 1 | A-D | Representative figure only | 
| Figure 2 | A | [Additional script](inst/Publication_Files/Fig2A_script.Rmd) |
|         | B |  [Additional script](inst/Publication_Files/Fig2B_script.Rmd) |
|         | C |  [Spatial Metabolomics Analysis Tutorial](https://genomicsmachinelearning.github.io/SpaMTP/articles/Mouse_Urinary_Bladder.html#:~:text=%23%23%23%20Subsets%20the%20original%20dataset%20to%20only%20include%20cluster%205%20and%206) |  
|         | D |  [Spatial Metabolomics Analysis Tutorial](https://genomicsmachinelearning.github.io/SpaMTP/articles/Mouse_Urinary_Bladder.html#:~:text=DEMsHeatmap-,(,-cluster_DEMs%2C%20only.pos) |  
|         | E |   [Additional script](inst/Publication_Files/Fig2E_script.Rmd)   |  
|         | F |   [Additional script](https://genomicsmachinelearning.github.io/SpaMTP/articles/Mouse_Urinary_Bladder.html#:~:text=plot%20the%20results%3A-,%23%23%20Custom,-palette%20for%20SpaMTP)   |  
|         | G |   [Spatial Metabolomics Analysis Tutorial](https://genomicsmachinelearning.github.io/SpaMTP/articles/Mouse_Urinary_Bladder.html#:~:text=key_pathways%20%3C%2D%20c(%22Biochemical)   |  
|         | H |   [Spatial Multi-Omics Analysis Tutorial](https://genomicsmachinelearning.github.io/SpaMTP/articles/Multi-Omic_Mouse_Brain.html#:~:text=ImageMZAnnotationPlot)   |  
|         | I |   [Spatial Multi-Omics Analysis Tutorial](https://genomicsmachinelearning.github.io/SpaMTP/articles/Multi-Omic_Mouse_Brain.html#:~:text=%3D%20FALSE)-,DimPlot,-(integrated.data)   |  
|         | J |   [Spatial Multi-Omics Analysis Tutorial](https://genomicsmachinelearning.github.io/SpaMTP/reference/Plot3DFeature.html)   |  
|         | K |   [Spatial Multi-Omics Analysis Tutorial](https://genomicsmachinelearning.github.io/SpaMTP/articles/Multi-Omic_Mouse_Brain.html#:~:text=Starting%20condition%3A%2011-,results,-%3C%2D%20cluster_DEMs%24)   |  
|         | L |   [Spatial Multi-Omics Analysis Tutorial](https://genomicsmachinelearning.github.io/SpaMTP/articles/Multi-Omic_Mouse_Brain.html#:~:text=disease%20to%20plot-,selected_pathways,-%3D%20c)   |  
|         | M |   [Spatial Multi-Omics Analysis Tutorial](https://genomicsmachinelearning.github.io/SpaMTP/articles/Multi-Omic_Mouse_Brain.html#:~:text=have%20a%20look%3A-,PathwayNetworkPlots,-(striatum.dhb)   |  
|         | N |   [Spatial Multi-Omics Analysis Tutorial](https://genomicsmachinelearning.github.io/SpaMTP/articles/Multi-Omic_Mouse_Brain.html#:~:text=this%20metabolite%20spatially%3A-,SpatialMZPlot,-(striatum.dhb)   |  
| Figure S1 | A-D |  Representative figure only |  
| Figure S2 | A-D |  Representative figure only | 
| Figure S3 | A-B |  [Additional script](inst/Publication_Files/FigS3_script.Rmd) | 
|           | C |  [Additional script](inst/Publication_Files/FigS3_script.Rmd) | 



